### ISSUE TITLE
more APIs

### ISSUE THREAD

**Issue by fahd200581** [Ifan24/youtube_dual_subtitles#11]
please add more APIs like google gemini, we can use it for free

**Comment by Ifan24** [comment]
Hi, sorry about not replying sooner, and thank you for the suggestion! I'm currently focusing my efforts on another project called [GPT Subtitler](https://gptsubtitler.com), so I might not have time to add new features to this project in the near future.

However, if you're looking to use the free Gemini API key, GPT Subtitler already supports this. Just select the Gemini model you want to use and add the API key in the translation settings. 

In my experience, it can provide similar or even better translation results compared to this project, since I've improved the prompt quite a bit and added many new features like Context Memory and translate with reflection.
